name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  async: ^2.11.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  get: ^4.6.6
  google_fonts: ^6.1.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/demon1.png
  image_dark: assets/images/demon1.png

  android_12:
    image: assets/images/demon1.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/demon1.png
    icon_background_color_dark: "#272727"





flutter:
  uses-material-design: true

  assets:
    - assets/images/demon1.png
    - assets/images/demon2.png
    - assets/images/demon4.png





