///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String cardsMastercard = 'assets/images/mastercard.png';
  static const String onboardimage1 = 'assets/images/demon2.png';
  static String onboardimage2 = 'assets/images/demon4.png';
  static String onboardimage3 = 'assets/images/demon2.png';
  static String homepage1 = 'assets/images/duplex.png';
  static const String homepage2 = 'assets/images/demon1.png';
  static const homepage3 = 'assets/images/demon2.png';
  static const String homepage4 = 'assets/images/demon4.png';
}
