///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String cardsMastercard = 'assets/cards/mastercard.png';
  static const String onboardimage1 = 'assets/images/demon2.png';
  static String onboardimage2 = 'assets/images/demon4.png';
  static String onboardimage3 = 'assets/images/demon2.png';
}
